version: 3

vars:
  IMG: ghrc.io/nuvolarisinc/nuvolaris-operator-ng
  BASETAG: 4.0.0-openserverless
  DOCKER_PLATFORM: "--platform linux/amd64,linux/arm64" 
  DOCKER_FLAGS: "--push"
  DRY: ""
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

tasks:

  image-tag: 
    silent: true
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag

  docker-login: 
    ignore_error: true
    cmds:
    - echo $GITHUB_TOKEN | docker login -u $GITHUB_USER --password-stdin  ghcr.io 
    - docker run -it --rm --privileged tonistiigi/binfmt --install all
    - docker buildx create --name mybuilder --bootstrap --use

  openwhisk-standalone:
    dir: openwhisk
    cmds:
    - bash ../build-standalone.bash
    status:
    - test -e bin/openwhisk-standalone.jar

  build:
    cmds:
    - task: openwhisk-standalone
    - >
      {{.DRY}} docker buildx build -t "{{.IMG}}:{{.TAG}}"  {{.DOCKER_PLATFORM}} . "{{.DOCKER_FLAGS}}"

  local-build:
    cmds:
    - task build DOCKER_PLATFORM="" DOCKER_FLAGS="--load"

  local-run:
    - docker run -ti "{{.IMG}}" bash
