version: 3

vars:
  IMG: ghrc.io/nuvolarisinc/nuvolaris-operator-ng
  BASETAG: 4.0.0-openserverless
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

  DRY: ""
  MULTI: ""

tasks:

  image-tag: 
    silent: true
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag

  docker-login: 
    ignore_error: true
    cmds:
    - echo $GITHUB_TOKEN | docker login -u $GITHUB_USER --password-stdin  ghcr.io 
    - docker run -it --rm --privileged tonistiigi/binfmt --install all
    - docker buildx create --name mybuilder --bootstrap --use

  openwhisk-standalone:
    dir: openwhisk
    cmds:
    - bash ../build-standalone.bash
    status:
    - test -e bin/openwhisk-standalone.jar

  build:
    cmds:
    - task: openwhisk-standalone
    - |
      if test -n "{{.PUSH}}"
      then {{.DRY}} docker buildx build -t "{{.IMG}}"  --platform linux/amd64,linux/arm64 . --push
      else {{.DRY}} docker buildx build -t "{{.IMG}}-$(arch)" . --push
      fi
